@bookstore = https://localhost:5001
@bookstore-cache = https://localhost:6001
@bookstore-audit = https://localhost:7001

@bookId = bd772b31-6d24-49d5-8314-af4c1de63a40
@userId= 8DD21F7D-0293-460F-869C-312BC7119BA6

### Get book
GET {{bookstore-cache}}/books/{{bookId}}

### Get user actions
GET {{bookstore-audit}}/audit


### Create new book
POST {{bookstore}}/books
content-type: application/json

{
    "title": "Domain-driven desig",
    "author": "Eric J. Evans",    
    "cost": 500,
    "inventoryAmount": 20,
    "userId": "{{userId}}"
}

### Update book
PUT {{bookstore}}/books/{{bookId}}
content-type: application/json

{
    "title": "Domain-driven design",
    "author": "Eric J. Evans",    
    "cost": 500,
    "inventoryAmount": 21,
    "userId": "{{userId}}"
}